### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [MattMav21/FilmUp-Project#1]
Hello FilmUp team!

I have reviewed your schema and wanted to leave you some comments. Please look these over, discuss them with your team, and feel free to ask me any questions that you may have.

## `WatchedMovies` and `Reviews` tables
- [x] These two tables contain much of the same information (`userId`, `movieId`). Which means that there is room for reducing duplicate storage! What do you think about adding the `content` column into the `WatchedMovies` table and removing the `reviews` table entirely? You could make it an optional (allowed to be null) column. 

## External API for Movies
- [x] Would this api include the `movies` table in addition to your `cast` and `movies_casts` table?
- [x] I think you should go for an external movies api! If you have any questions about implementing this, reach out to JM or me.

**Comment by guipace** [comment]
Discussed feedback with JM and refactored the database schema simplifying the watched status & review functionality.

Discussed implementing an external API to import movies that don't exist in our database as a bonus feature.
